#!/bin/sh

ctags --languages=asm,c,c++,make,ruby,sh,java,HTML --langmap=c:.c.h.x,make:.mk.mak --exclude=.svn --links=no -R .

find . -type f -name '*.java' -o -name '*.cpp' -o -name '*.c' -o -name '*.h' -o -name '*.xml' -o -name '*.mk' -o -name '*.mak' > cscope.files
cscope -R -b
rm cscope.files 
